# -*- coding: utf-8 -*-
"""Builds the Question Bank and Answers PDFs for CAIE AS Business 9609."""
import pdfgen

# ----------------------------------------------------------------------------
# QUESTIONS
# ----------------------------------------------------------------------------
Q = []
def q(t): Q.append(('body', t))
def qh1(t): Q.append(('h1', t))
def qh2(t): Q.append(('h2', t))
def qsp(): Q.append(('spacer', ''))

Q.append(('title', 'AS Business 9609 - Complete Question Bank'))
Q.append(('body', 'Cambridge International AS Level Business (9609). Syllabus 2026-2028. '
    'Prepared for the Oct/Nov 2026 exam. Answer every question in this booklet and you '
    'will have covered the entire AS syllabus. Model answers are in the separate Answers booklet.'))
Q.append(('body', 'Marks in brackets guide the depth expected. [K]=knowledge, '
    '[App]=apply to context, [An]=analysis, [Ev]=evaluation/judgement, [Calc]=calculation.'))
qsp()

# ============================= TOPIC 1 =====================================
qh1('TOPIC 1: Business and its Environment')

qh2('1.1.1 The nature of business activity')
q('1. State the main purpose of business activity. [2] [K]')
q('2. Define the four factors of production and give one example of each. [4] [K]')
q('3. State the reward earned by each factor of production. [4] [K]')
q('4. Define "added value" and state the formula used to calculate it. [3] [K]')
q('5. Explain two ways a business could add value to its products. [4] [An]')
q('6. Explain the economic problem of scarcity and why it forces choice. [4] [An]')
q('7. Define opportunity cost and give one business example. [3] [App]')
q('8. Explain what is meant by a "dynamic business environment" and give two examples of change a business must respond to. [4] [An]')
q('9. Analyse two reasons why a new business might fail in its first year. [6] [An]')
q('10. Distinguish between a local, national, international and multinational business. [4] [K]')

qh2('1.1.2 Entrepreneurs and intrapreneurs')
q('11. State four qualities needed by a successful entrepreneur. [4] [K]')
q('12. Distinguish between an entrepreneur and an intrapreneur. [3] [K]')
q('13. Explain the role of intrapreneurship in the ongoing success of an established business. [5] [An]')
q('14. Analyse three barriers to entrepreneurship a person may face when starting a business. [6] [An]')
q('15. Distinguish between business risk and uncertainty, using examples. [4] [App]')
q('16. Evaluate the importance of business enterprise to the economic development of a developing country. [10] [Ev]')

qh2('1.1.3 Business plans')
q('17. Define a business plan and state its main purpose. [3] [K]')
q('18. State five key elements you would expect to find in a business plan. [5] [K]')
q('19. Explain two benefits to an entrepreneur of writing a business plan. [4] [An]')
q('20. Evaluate whether a detailed business plan guarantees the success of a start-up. [10] [Ev]')

qh2('1.2.1 Economic sectors')
q('21. Define the primary, secondary, tertiary and quaternary sectors, with one example each. [4] [K]')
q('22. Distinguish between the public sector and the private sector. [2] [K]')
q('23. Explain two reasons why the relative importance of the secondary sector has declined in many developed economies. [4] [An]')
q('24. Analyse two consequences for an economy of de-industrialisation. [6] [An]')

qh2('1.2.2 Business ownership')
q('25. Distinguish between limited and unlimited liability, and explain why the difference matters. [4] [K]')
q('26. State two advantages and two disadvantages of operating as a sole trader. [4] [K]')
q('27. Explain two differences between a private limited company (Ltd) and a public limited company (Plc). [4] [An]')
q('28. Explain how a franchise works and give one benefit to the franchisee and one to the franchisor. [4] [An]')
q('29. Explain the aims of a social enterprise and how it differs from a typical private company. [4] [K]')
q('30. Analyse the advantages and disadvantages to a growing business of changing from an Ltd to a Plc. [8] [An]')
q('31. A joint venture and a co-operative are both forms of ownership. Explain the key feature of each. [4] [K]')
q('32. Evaluate the most appropriate form of ownership for two friends opening a small restaurant with limited savings. [10] [Ev/App]')

qh2('1.3 Size of business')
q('33. State four methods of measuring the size of a business. [4] [K]')
q('34. Explain why using number of employees can be a misleading measure of size for a capital-intensive firm. [4] [An]')
q('35. State two advantages and two disadvantages of being a small business. [4] [K]')
q('36. Analyse two strengths and two weaknesses of a family business. [6] [An]')
q('37. Explain two reasons why small businesses are important to an economy. [4] [An]')

qh2('1.3.3 Business growth')
q('38. Distinguish between internal (organic) growth and external growth. [3] [K]')
q('39. Define and give an example of: horizontal integration, backward vertical integration, forward vertical integration, and conglomerate diversification. [8] [K]')
q('40. Distinguish between a friendly merger and a hostile takeover. [2] [K]')
q('41. Analyse the possible impact of a takeover on two different stakeholder groups. [6] [An]')
q('42. Explain two reasons why a merger or takeover may fail to achieve its objectives. [4] [An]')
q('43. Distinguish between a joint venture and a strategic alliance as methods of external growth. [3] [K]')
q('44. Evaluate whether organic growth or growth by takeover is the better strategy for a medium-sized manufacturer. [12] [Ev]')

qh2('1.4 Business objectives')
q('45. State three objectives a business in the private sector might have. [3] [K]')
q('46. Explain two reasons why setting objectives is important for a business. [4] [An]')
q('47. Explain the "triple bottom line" and how it relates to corporate social responsibility (CSR). [5] [K]')
q('48. Explain the relationship between mission statement, aims, objectives, strategy and tactics. [5] [K]')
q('49. State what each letter of SMART stands for and explain why SMART objectives are useful. [5] [K]')
q('50. Explain the stages of business decision-making and the role objectives play in them. [6] [An]')
q('51. Explain how and why a business objectives might change as it moves from start-up to being well established. [4] [An]')
q('52. Analyse how acting ethically might influence a business objectives and its profits. [6] [An]')

qh2('1.5 Stakeholders')
q('53. Define "stakeholder" and give two examples of internal and two of external stakeholders. [4] [K]')
q('54. Explain the roles, rights and responsibilities of employees as stakeholders. [4] [K]')
q('55. Explain how a decision to relocate production overseas could affect three different stakeholder groups. [6] [App/An]')
q('56. Explain why and how a business should be accountable to its stakeholders. [4] [An]')
q('57. Analyse how conflict might arise between shareholders and employees when a business tries to cut costs. [6] [An]')
q('58. Evaluate the view that a business should always put the interests of its shareholders first. [12] [Ev]')

# ============================= TOPIC 2 =====================================
qh1('TOPIC 2: Human Resource Management')

qh2('2.1 HRM, workforce planning, recruitment')
q('59. Explain the role of HRM in meeting the objectives of a business. [4] [An]')
q('60. Define a workforce plan and explain two reasons a business needs one. [4] [K]')
q('61. [Calc] A business had 15 employees leave during the year and employed an average of 120 staff. Calculate the labour turnover. [2] [Calc]')
q('62. Explain two implications for a business of a high rate of labour turnover. [4] [An]')
q('63. Distinguish between a job description and a person specification. [2] [K]')
q('64. Explain two advantages of internal recruitment and two of external recruitment. [4] [An]')
q('65. State four methods a business could use to select the best candidate from a shortlist. [4] [K]')
q('66. Define an employment contract and state two things it would contain. [3] [K]')

qh2('2.1.4-2.1.7 Redundancy, welfare, training, relations')
q('67. Distinguish between redundancy and dismissal. [3] [K]')
q('68. Distinguish between voluntary and involuntary redundancy, and between fair and unfair dismissal. [4] [K]')
q('69. Explain the term "work-life balance" and how improving it could benefit a business. [4] [An]')
q('70. Analyse the benefits to a business of a diverse and equal workplace. [6] [An]')
q('71. Distinguish between induction, on-the-job and off-the-job training. [3] [K]')
q('72. Analyse the impact on a business of investing heavily in training its workforce. [6] [An]')
q('73. Explain how employee development can encourage multi-skilling and flexibility. [4] [An]')
q('74. Explain the role of a trade union in collective bargaining and one impact on the employer. [4] [An]')

qh2('2.2 Motivation')
q('75. Explain why it is important for a business to motivate its employees. [4] [An]')
q('76. Outline the main idea of F.W. Taylor scientific management and how workers should be paid according to him. [4] [K]')
q('77. Explain Elton Mayo human relations theory and the Hawthorne effect. [4] [K]')
q('78. Draw and label Maslow hierarchy of needs and explain how a manager could use it to motivate staff. [6] [K/An]')
q('79. Explain Herzberg two-factor theory, distinguishing between hygiene factors and motivators. [5] [K]')
q('80. Outline McClelland three needs and Vroom expectancy theory. [5] [K]')
q('81. Define and give an example of: piece rate, commission, profit sharing, performance-related pay, and fringe benefits. [5] [K]')
q('82. Explain three non-financial methods of motivating employees. [6] [An]')
q('83. Evaluate whether financial or non-financial motivators are more effective for motivating skilled workers. [12] [Ev]')

qh2('2.3 Management')
q('84. State the four traditional functions of management. [4] [K]')
q('85. Explain the difference between the ideas of Fayol and Mintzberg on the role of managers. [4] [K]')
q('86. Describe autocratic, democratic, laissez-faire and paternalistic management styles. [4] [K]')
q('87. Explain McGregor Theory X and Theory Y and how each affects management style. [5] [An]')
q('88. Evaluate the most appropriate management style for a business facing a sudden financial crisis. [10] [Ev]')

# ============================= TOPIC 3 =====================================
qh1('TOPIC 3: Marketing')

qh2('3.1 The nature of marketing')
q('89. Define marketing and state two possible marketing objectives. [3] [K]')
q('90. Explain the link between marketing objectives and corporate objectives. [4] [An]')
q('91. State two factors that influence the demand for a product and two that influence its supply. [4] [K]')
q('92. Explain how a fall in price and a rise in consumer incomes could each affect demand. [4] [An]')
q('93. Distinguish between product orientation and customer (market) orientation. [3] [K]')
q('94. [Calc] A business sells $4m of goods in a market worth $50m. Calculate its market share. If the market grew from $50m to $55m, calculate the market growth. [4] [Calc]')
q('95. Explain two implications for a business of a falling market share in a growing market. [4] [An]')
q('96. Explain two ways marketing for a B2B product might differ from marketing for a B2C product. [4] [An]')
q('97. Compare the features of mass marketing and niche marketing. [4] [K]')
q('98. Analyse the advantages and disadvantages of niche marketing for a small business. [6] [An]')
q('99. Explain the three main methods of market segmentation with an example of each. [6] [K]')
q('100. Analyse the benefits and costs of customer relationship marketing (CRM). [6] [An]')

qh2('3.2 Market research')
q('101. State two purposes of market research. [2] [K]')
q('102. Distinguish between primary and secondary research and give two examples of each. [4] [K]')
q('103. Explain the usefulness and one limitation of primary research data. [4] [An]')
q('104. Explain why a business uses sampling and two limitations of sampling. [4] [An]')
q('105. Distinguish between quantitative and qualitative data. [2] [K]')
q('106. Explain two factors that affect the reliability of market research data. [4] [An]')

qh2('3.3 The marketing mix')
q('107. State the 4Ps of the marketing mix. [4] [K]')
q('108. Distinguish between goods and services, and between tangible and intangible product attributes. [4] [K]')
q('109. Explain the terms "product differentiation" and "unique selling point (USP)". [4] [K]')
q('110. Draw the product life cycle and label its stages. Explain two extension strategies. [6] [K/An]')
q('111. Explain the four categories of the Boston Matrix and how a business would treat a product in each. [8] [K/An]')
q('112. Explain the objectives and usefulness of the following pricing methods: penetration, skimming, price discrimination, dynamic, psychological, cost-based, competitive. [8] [K]')
q('113. Explain the difference between advertising, sales promotion and direct promotion. [6] [K]')
q('114. Analyse two developments in digital promotion and their benefits to a business. [6] [An]')
q('115. Explain the role of packaging and branding in promotion. [4] [An]')
q('116. Explain two channels of distribution and the difference between physical and digital distribution. [4] [K]')
q('117. Evaluate the marketing mix a business should use when launching a new premium smartphone. [12] [Ev/App]')

# ============================= TOPIC 4 =====================================
qh1('TOPIC 4: Operations Management')

qh2('4.1 The nature of operations')
q('118. Explain the transformational process using the terms inputs, process and outputs. [4] [K]')
q('119. Explain how operations can add value to a product. [3] [An]')
q('120. Distinguish between efficiency, effectiveness, productivity and sustainability. [4] [K]')
q('121. [Calc] A factory produces 12,000 units per week with 40 workers. Calculate labour productivity per worker. [2] [Calc]')
q('122. Analyse the impact on a business of introducing measures to make operations more sustainable. [6] [An]')
q('123. Compare the benefits and limitations of capital-intensive and labour-intensive operations. [6] [An]')
q('124. Explain the difference between job, batch, flow and mass customisation production. [8] [K]')
q('125. Explain two problems a business may face when changing from batch to flow production. [4] [An]')

qh2('4.2 Inventory management')
q('126. State the three types of inventory a manufacturer holds. [3] [K]')
q('127. Explain two costs and two benefits of holding inventory. [4] [An]')
q('128. Define buffer inventory, re-order level and lead time. [3] [K]')
q('129. Using an inventory control chart, explain what happens to stock levels between deliveries. [4] [An]')
q('130. Explain the importance of supply chain management to a business. [4] [An]')
q('131. Distinguish between JIT and JIC inventory management and analyse the impact of adopting JIT. [8] [An]')

qh2('4.3 Capacity utilisation and outsourcing')
q('132. [Calc] A hotel has 200 rooms and on average 150 are occupied each night. Calculate its capacity utilisation. [2] [Calc]')
q('133. Explain two problems of operating at very low capacity utilisation and two of operating at 100%. [4] [An]')
q('134. Explain two methods a business could use to improve its capacity utilisation. [4] [An]')
q('135. Analyse the benefits and drawbacks of outsourcing part of a business operations. [6] [An]')

# ============================= TOPIC 5 =====================================
qh1('TOPIC 5: Finance and Accounting')

qh2('5.1 Business finance')
q('136. Explain why a business needs finance to start up, to grow, and to survive. [6] [K]')
q('137. Distinguish between a short-term and a long-term need for finance. [3] [K]')
q('138. Explain the difference between cash and profit, and why a profitable business can still fail. [5] [An]')
q('139. Distinguish between bankruptcy, liquidation and administration. [3] [K]')
q('140. [Calc] A business has current assets of $80,000 and current liabilities of $55,000. Calculate its working capital and comment on it. [3] [Calc]')
q('141. Explain how a business could better manage its trade receivables and trade payables. [4] [An]')
q('142. Distinguish between capital expenditure and revenue expenditure with examples. [4] [K]')

qh2('5.2 Sources of finance')
q('143. Explain how the form of business ownership affects the sources of finance available. [4] [An]')
q('144. List four internal and six external sources of finance. [5] [K]')
q('145. Explain the following sources: debt factoring, sale and leaseback, venture capital, crowdfunding, micro-finance, trade credit. [6] [K]')
q('146. Explain four factors that influence a business choice of source of finance. [4] [An]')
q('147. Recommend and justify a suitable source of finance for (a) a sole trader buying a $3,000 laptop and (b) a Plc funding a $40m factory. [6] [Ev/App]')

qh2('5.3 Cash flow')
q('148. Define a cash flow forecast and state two reasons a business prepares one. [3] [K]')
q('149. [Calc] In March, a business has an opening balance of $5,000, cash inflows of $22,000 and cash outflows of $26,000. Calculate the net cash flow and the closing balance. This becomes the opening balance for April. [4] [Calc]')
q('150. Explain three methods a business could use to improve its cash flow. [6] [An]')

qh2('5.4 Costs')
q('151. Distinguish between fixed, variable, direct and indirect costs, with an example of each. [4] [K]')
q('152. [Calc] Fixed costs are $20,000, variable cost per unit is $6, and 5,000 units are produced. Calculate total cost and average cost per unit. [4] [Calc]')
q('153. Distinguish between full costing and contribution costing. [4] [K]')
q('154. Explain the difference between contribution and profit. [3] [K]')
q('155. [Calc] Selling price is $15, variable cost per unit is $9, fixed costs are $30,000. Calculate contribution per unit, and the profit if 8,000 units are sold. [4] [Calc]')
q('156. Explain how contribution costing is used to make a special order decision. [5] [An]')
q('157. Explain two limitations of contribution costing. [4] [An]')

qh2('5.4.4 Break-even analysis')
q('158. Define break-even and state the formula for the break-even level of output. [3] [K]')
q('159. [Calc] A firm has fixed costs of $48,000, sells at $20 per unit and has variable costs of $12 per unit. Calculate: (a) contribution per unit, (b) break-even output, (c) the margin of safety if current output is 8,000 units, (d) the profit at 8,000 units. [6] [Calc]')
q('160. Explain what the margin of safety tells a business. [3] [An]')
q('161. Explain two uses and two limitations of break-even analysis. [6] [An]')

qh2('5.5 Budgets and variances')
q('162. Define a budget and explain two uses of budgets to a business. [4] [K]')
q('163. Explain the difference between incremental, flexible and zero-based budgeting. [6] [K]')
q('164. Explain two benefits and two drawbacks of using budgets. [4] [An]')
q('165. Distinguish between a favourable and an adverse variance. [3] [K]')
q('166. [Calc] Budgeted sales revenue was $60,000 but actual revenue was $54,000. Budgeted costs were $40,000 but actual costs were $37,000. Calculate each variance and state whether it is favourable or adverse. [4] [Calc]')
q('167. Evaluate whether budgeting always improves the performance of a business. [10] [Ev]')

qsp()
Q.append(('body', 'END OF QUESTION BANK - Total 167 questions covering the full AS syllabus.'))


# ----------------------------------------------------------------------------
# ANSWERS
# ----------------------------------------------------------------------------
A = []
def a(t): A.append(('body', t))
def ab(t): A.append(('bullet', t))
def ah1(t): A.append(('h1', t))
def ah2(t): A.append(('h2', t))
def asp(): A.append(('spacer', ''))

A.append(('title', 'AS Business 9609 - Answers & Mark Guidance'))
A.append(('body', 'Model answers and key points for the Question Bank. These are indicative: in the '
    'exam, application to the specific case and a supported judgement earn the top marks.'))
asp()

ah1('TOPIC 1: Business and its Environment')
ah2('1.1.1 Nature of business activity')
a('1. To combine resources to produce goods/services that satisfy customers needs and wants, usually to make a profit.')
a('2/3. Land (natural resources, e.g. farmland) -> rent; Labour (human effort, e.g. workers) -> wages; Capital (man-made aids, e.g. machinery) -> interest; Enterprise (the risk-taking entrepreneur) -> profit.')
a('4. Added value = selling price - cost of bought-in materials/inputs. It is the increase in worth created during production.')
a('5. Branding (allows premium price); improved quality/design; better customer service; convenience/speed; unique features. Each raises what customers will pay above input cost.')
a('6. Resources are scarce but wants are unlimited (the economic problem). Because you cannot have everything, a choice must be made about how to use limited resources.')
a('7. Opportunity cost = the benefit of the next best alternative given up. E.g. spending funds on new machinery means they cannot be spent on a marketing campaign.')
a('8. Dynamic environment = one that constantly changes. Examples: changing consumer tastes, new technology, new competitors, economic/legal changes. Firms must adapt to survive.')
a('9. Any two developed: poor cash flow/finance management (cannot pay bills -> insolvency); lack of demand/poor market research; weak management decisions; too much competition; failure to adapt to change.')
a('10. Local = one town/area; National = throughout one country; International = trades/sells in more than one country; Multinational = has operations/production bases in more than one country.')

ah2('1.1.2 Entrepreneurs and intrapreneurs')
a('11. Any four: innovation/creativity, risk-taking, self-confidence, determination/resilience, hard work, leadership, self-motivation, ability to spot opportunities.')
a('12. Entrepreneur sets up and takes the personal financial risk of a NEW business; an intrapreneur is an EMPLOYEE who innovates within an existing business without bearing the personal financial risk.')
a('13. Intrapreneurs generate new products/processes and ideas from within, keeping the firm innovative and competitive, improving efficiency and helping it respond to change - all without the individual risking their own money.')
a('14. Any three developed: lack of finance/difficulty raising capital; lack of skills/experience; strong competition from established firms; fear of failure/losing personal assets; legal red tape; poor economic conditions.')
a('15. Risk = outcomes that can be identified and their probability estimated/insured (e.g. risk of some stock being unsold). Uncertainty = unpredictable events that cannot be foreseen or measured (e.g. a sudden pandemic or war).')
a('16. Evaluation: enterprise creates jobs (lower unemployment), raises output/GDP, drives innovation, increases exports and tax revenue, raises living standards. Judgement: hugely important BUT depends on access to finance, education, infrastructure and government support; without these, enterprise alone cannot develop a country.')

ah2('1.1.3 Business plans')
a('17. A document setting out the business idea, objectives, strategy, market and financial forecasts. Main purpose: to clarify the idea and help raise finance.')
a('18. Any five: executive summary/idea; products/services; market & research; marketing plan (4Ps); operations/location; management/personnel; financial forecasts (cash flow, projected profit, start-up costs, sources of finance).')
a('19. Forces owner to research and think the idea through; helps obtain finance from banks/investors; sets targets to measure progress; identifies problems early; aids decision-making. (Explain any two.)')
a('20. Evaluation: a plan reduces risk, aids finance and planning, BUT is based on forecasts/assumptions that may be wrong, becomes outdated in a dynamic environment, and does not control demand, competition or the economy. Conclusion: it improves the chance of success but does NOT guarantee it.')

ah2('1.2.1 Economic sectors')
a('21. Primary = extraction (farming/mining); Secondary = manufacturing (car making); Tertiary = services (retail/banking); Quaternary = knowledge/information services (R&D, ICT, consultancy).')
a('22. Public sector = owned/controlled by government; Private sector = owned by private individuals/firms (usually profit-seeking).')
a('23. Rising incomes shift demand to services; cheaper manufacturing abroad; automation reduces manufacturing jobs; growth of the knowledge economy.')
a('24. Structural unemployment in declining regions; need for retraining/new skills; regional decline balanced by growth in service areas; changing skill demands.')

ah2('1.2.2 Business ownership')
a('25. Unlimited liability = owner personally responsible for all debts (personal assets at risk) - sole traders/partnerships. Limited liability = losses limited to the amount invested; personal assets protected - Ltd/Plc. Matters because it affects personal financial risk and willingness to invest.')
a('26. Advantages: easy/cheap to set up, full control, keeps all profit, privacy. Disadvantages: unlimited liability, hard to raise finance, long hours, no continuity.')
a('27. Ltd sells shares privately (to known people) and need not publish full accounts; Plc sells shares to the public on a stock exchange, must publish full accounts, can raise far more capital but risks takeover and divorce of ownership and control.')
a('28. Franchisee buys the right to trade under the franchisor brand for fees/royalties. Franchisee benefit: proven idea, brand, support (lower risk). Franchisor benefit: rapid expansion with less capital and franchisee investment/effort.')
a('29. Social enterprise trades to achieve social/environmental aims and reinvests profits (triple bottom line), whereas a typical private company aims mainly to maximise profit for owners.')
a('30. Advantages: raises much more capital via public share issue, retains limited liability, greater status, funds growth. Disadvantages: loss of control/ownership diluted, risk of hostile takeover, must publish accounts, divorce of ownership and control, short-term profit pressure.')
a('31. Joint venture = two businesses set up a new separate business together, sharing costs/risk. Co-operative = owned and democratically run by its members (one member, one vote), sharing profits.')
a('32. Likely partnership (more capital, shared workload/skills) or private limited company (limited liability protects savings). Judgement should weigh liability protection vs simplicity/cost and control - Ltd best if protecting personal assets is the priority.')

ah2('1.3 Size and growth')
a('33. Number of employees, revenue (turnover), capital employed, market share, market capitalisation.')
a('34. A capital-intensive firm uses machines not people, so it may have huge output/revenue with very few staff - employee numbers understate its true size. Better to use several measures.')
a('35. Advantages: flexible/quick to respond, personal service, low overheads. Disadvantages: hard to raise finance, no economies of scale, vulnerable to competition, reliance on few people.')
a('36. Strengths: commitment/loyalty, long-term view, trust, quick decisions. Weaknesses: family conflict, succession problems, unqualified relatives given jobs, resistance to outside ideas.')
a('37. Create jobs; encourage competition/innovation; supply larger firms; provide local services; source of future large firms; provide choice/variety.')
a('38. Organic = growth using the firm own resources (more outlets/products). External = growth via merger/takeover, JV or alliance with another firm.')
a('39. Horizontal = same industry/stage (two car makers) -> market share/economies of scale. Backward vertical = with a supplier (car maker buys tyre firm) -> control of supplies. Forward vertical = with a customer/distributor (car maker buys dealerships) -> control of distribution. Conglomerate = unrelated industries (car maker buys a hotel chain) -> spreads risk.')
a('40. Friendly merger = both firms agree to join. Hostile takeover = the target board does NOT agree to being bought.')
a('41. Workers: risk of redundancy/uncertainty, low morale (or new opportunities). Shareholders: possible higher returns or high integration costs. Customers: possible price/choice changes. (Develop two.)')
a('42. Culture clash; poor integration; diseconomies of scale; overestimated synergies; high cost; staff resistance/low morale.')
a('43. Joint venture creates a NEW separate legal entity owned by the partners; a strategic alliance is a looser cooperation agreement with no new company formed.')
a('44. Organic: lower risk, easier to manage, keeps control, but slow. Takeover: fast, instant market share/synergies, but risky (culture clash, high cost, integration problems). Judgement: depends on urgency, finance available, management capability and the market - e.g. takeover if speed to gain market share is essential and finance is available.')

ah2('1.4-1.5 Objectives and stakeholders')
a('45. Survival, profit maximisation, growth, increasing market share, protecting reputation.')
a('46. Give direction/focus; aid decision-making; motivate staff; allow performance to be measured; coordinate the business. (Explain two.)')
a('47. Triple bottom line = measuring success on profit (economic), people (social) and planet (environmental). CSR = the responsibility of a business to society/environment beyond profit; the triple bottom line is how CSR performance is measured.')
a('48. Mission = overall purpose; aims = broad long-term goals; objectives = specific measurable goals from the aims; strategy = long-term plan to achieve them; tactics = short-term actions to carry out the strategy.')
a('49. Specific, Measurable, Achievable, Realistic, Time-limited. Useful because they are clear, can be reviewed/measured, motivate staff and guide decisions.')
a('50. Set objectives -> gather data -> analyse options -> make decision -> implement -> review against objectives. Objectives provide the criteria against which options are judged and results reviewed.')
a('51. Start-ups focus on survival; once established the focus shifts to growth/profit/market share; in a recession it may return to survival. Changes as the market, competition and finances change.')
a('52. Ethical actions (fair pay, honest marketing, no child labour) may raise costs and reduce short-term profit, BUT improve reputation, customer loyalty, staff motivation and long-term profit. There is often a profit-vs-ethics trade-off.')
a('53. Stakeholder = any group/individual affected by or able to affect the business. Internal: owners/shareholders, managers, employees. External: customers, suppliers, government, community, lenders.')
a('54. Role: provide labour. Rights: fair pay, safe conditions, contract. Responsibilities: work productively, follow rules, act honestly.')
a('55. Employees (job losses at home, morale); local community (lost jobs/spending); shareholders (lower costs/higher profit); customers (possible price/quality change); overseas workers (new jobs). Apply to context.')
a('56. Accountability = answering to stakeholders via publishing accounts, obeying laws, CSR reporting. Builds trust, reputation and support and reduces conflict.')
a('57. Cost-cutting (e.g. lower wages/redundancies) raises profit for shareholders but reduces pay/security for employees, lowering morale - the two groups aims conflict.')
a('58. Shareholders provide capital and bear risk, so their returns matter, BUT ignoring employees, customers, community and environment harms reputation, motivation and long-term profit. Judgement: a balanced stakeholder approach usually serves long-term shareholder interest best.')

ah1('TOPIC 2: Human Resource Management')
a('59. HRM ensures the business has the right number of suitably skilled, trained and motivated staff to achieve its objectives (planning, recruitment, training, motivation, relations).')
a('60. Workforce plan = forecast of the number and skills of workers needed in future and how to meet that need. Reasons: plan for expansion, new technology, retirements; avoid over/under-staffing.')
a('61. Labour turnover = (15/120) x 100 = 12.5%.')
a('62. High turnover: higher recruitment/training costs, lost productivity/experience, low morale; (could bring fresh ideas / remove weak performers).')
a('63. Job description = duties/tasks/responsibilities of the role. Person specification = the skills, qualifications and qualities the ideal candidate needs.')
a('64. Internal: cheaper/faster, known candidate, motivates staff (but limited pool, no new ideas). External: fresh ideas, wider pool, new skills (but slower, costlier, unknown candidate).')
a('65. CV/resume and application forms, interviews, references, testing (aptitude/psychometric), assessment centres.')
a('66. Legal document stating terms and conditions of employment. Contains: pay, hours, duties, holiday, notice period.')
a('67. Redundancy = job no longer exists (not the worker fault), e.g. restructuring/automation. Dismissal = contract ended due to the worker conduct or performance.')
a('68. Voluntary redundancy: worker chooses to leave (often for a payment). Involuntary: business selects who leaves. Fair dismissal: valid reason + correct procedure. Unfair dismissal: no valid reason/procedure (illegal).')
a('69. Work-life balance = helping staff balance work with personal life (flexible/remote hours). Benefits: higher morale/productivity, lower absence and turnover, easier recruitment.')
a('70. Wider talent pool, more ideas/creativity, better reputation, avoids discrimination claims, better serves a diverse customer base. (Develop analysis.)')
a('71. Induction = introducing new staff to the business/role. On-the-job = training while working. Off-the-job = training away from the workplace (courses).')
a('72. Higher productivity/quality, better motivation, more flexibility, fewer accidents - BUT costs time/money and trained staff may leave for competitors.')
a('73. Developing staff to perform several roles means they can cover absences, adapt to demand changes and be redeployed - increasing flexibility and efficiency.')
a('74. Union negotiates pay/conditions collectively for members (collective bargaining). Impact on employer: single point of negotiation but slower decisions and possible strike action.')
a('75. Motivated staff are more productive, produce higher quality, have lower absence/turnover and help achieve objectives.')
a('76. Taylor: workers are motivated mainly by money; break jobs into simple tasks and pay by piece rate (per unit) to maximise output.')
a('77. Mayo: social needs/attention/teamwork motivate workers (Hawthorne effect - productivity rose when workers felt noticed and involved), not just pay.')
a('78. Bottom to top: Physiological, Safety, Social, Esteem, Self-actualisation. Manager identifies the level a worker is on and offers the next level (e.g. teamwork for social, recognition for esteem).')
a('79. Hygiene factors (pay, conditions, supervision, security) cause dissatisfaction if poor but do not motivate; motivators (achievement, recognition, responsibility, the work itself, advancement) truly motivate -> use job enrichment.')
a('80. McClelland: people are driven by needs for Achievement, Affiliation and Power in different amounts. Vroom expectancy: motivation = expectancy x instrumentality x valence (belief effort leads to performance, performance leads to reward, and the reward is valued).')
a('81. Piece rate = pay per unit produced. Commission = % of sales. Profit sharing = share of company profit. PRP = pay linked to appraised performance. Fringe benefits = non-cash perks (company car, health insurance).')
a('82. Any three developed: promotion opportunities, job enrichment, empowerment, team working, participation, status, job rotation/redesign, recognition.')
a('83. Financial motivators meet basic/security needs and reward output, BUT Herzberg says pay only prevents dissatisfaction. For skilled workers, non-financial motivators (responsibility, recognition, empowerment) often motivate more. Judgement: depends on the individual and their needs - usually a combination is best.')
a('84. Planning, organising, directing (commanding/coordinating), controlling.')
a('85. Fayol described five FUNCTIONS managers perform (plan, organise, command, coordinate, control). Mintzberg described ten ROLES in three groups (interpersonal, informational, decisional), arguing managers work is fragmented and reactive.')
a('86. Autocratic: manager decides alone, one-way orders. Democratic: decisions shared/consulted. Laissez-faire: staff left to decide. Paternalistic: manager decides but in staff best interests and consults.')
a('87. Theory X: assumes staff are lazy and avoid responsibility -> close control/autocratic. Theory Y: assumes staff enjoy work and seek responsibility -> empower/democratic. The assumption drives the style chosen.')
a('88. In a crisis, an autocratic style allows fast, firm decisions, BUT can harm morale. Democratic/paternalistic may keep staff support. Judgement: autocratic likely best short-term for speed, moving to a more consultative style once stable.')

ah1('TOPIC 3: Marketing')
a('89. Marketing = anticipating, identifying and satisfying customer needs profitably. Objectives: increase sales, market share, brand awareness, enter new markets.')
a('90. Marketing objectives must support corporate objectives - e.g. a corporate goal of growth translates into a marketing objective to raise market share by a set %.')
a('91. Demand: price, incomes, tastes/fashion, price of substitutes, advertising. Supply: costs of production, technology, taxes/subsidies, number of producers, weather.')
a('92. A fall in price raises quantity demanded; a rise in incomes raises demand for normal goods (curve shifts right), so more is bought at each price.')
a('93. Product orientation: make the product then find buyers (product-led). Market orientation: research customer needs first, then produce to match (lower risk).')
a('94. Market share = (4/50) x 100 = 8%. Market growth = ((55-50)/50) x 100 = 10%.')
a('95. Losing share while the market grows means rivals are winning new customers faster - signals weak competitiveness, lost economies of scale, and lower future revenue/profit.')
a('96. B2B: fewer/larger buyers, rational/technical appeal, personal selling, negotiated prices, long-term relationships. B2C: mass advertising, emotional/brand appeal, retail channels.')
a('97. Mass = whole/large market, one product, high volume, economies of scale. Niche = small specific segment, lower volume, higher margins, less competition.')
a('98. Advantages: less competition, higher prices/margins, loyal focused customers. Disadvantages: small sales volume, vulnerable if the segment shrinks, limited growth, risk if one product fails.')
a('99. Geographic (by region/climate), demographic (age, gender, income, occupation), psychographic (lifestyle, values, personality). Give an example of each.')
a('100. Benefits: repeat sales, loyalty, word-of-mouth, cheaper than winning new customers, useful data. Costs: database/technology systems, staff training, loyalty scheme costs.')
a('101. Identify market features (size, growth, competitors) and customer characteristics, wants and needs; reduce the risk of decisions.')
a('102. Primary = new first-hand data (surveys, interviews, observation, focus groups). Secondary = existing data (government stats, market reports, internet, internal records).')
a('103. Primary is up-to-date, specific and exclusive to the firm; limitation: expensive, time-consuming and can be biased if the sample is poor.')
a('104. Sampling saves time/cost as you cannot ask everyone. Limitations: if the sample is too small or unrepresentative it causes bias and unreliable results.')
a('105. Quantitative = numerical data (how many/how much). Qualitative = opinions/reasons (why), giving deeper insight but harder to measure.')
a('106. Sample size and representativeness; how up-to-date the data is; the research method; honesty of respondents; bias in questions.')
a('107. Product, Price, Promotion, Place.')
a('108. Goods = tangible (physical); services = intangible. Tangible attributes = physical features/quality/design; intangible = brand image, reputation, after-sales service.')
a('109. Product differentiation = making a product distinct from rivals. USP = the specific feature that makes it stand out and gives a reason to buy.')
a('110. Stages: Development, Introduction, Growth, Maturity, Decline. Extension strategies (in maturity): new markets, new uses, new packaging, price changes, promotion, product updates.')
a('111. Star (high share, high growth) - invest to grow. Cash cow (high share, low growth) - milk for cash. Question mark/problem child (low share, high growth) - invest or drop. Dog (low share, low growth) - consider dropping. Cash cows fund stars and question marks.')
a('112. Penetration: low price to enter/gain share. Skimming: high initial price then lower (new tech). Price discrimination: different prices to different groups/times. Dynamic: price changes with demand in real time. Psychological: e.g. 9.99. Cost-based: mark-up on cost. Competitive: in line with rivals.')
a('113. Advertising = paid non-personal media to inform/persuade. Sales promotion = short-term incentives (discounts, BOGOF, coupons). Direct promotion = targeted contact (direct mail, email, telemarketing).')
a('114. Any two: social media, influencer marketing, SEO, pay-per-click, content/viral marketing. Benefits: cheap, wide reach, targeted, measurable, interactive.')
a('115. Packaging protects, informs, attracts attention and reinforces brand. Branding creates recognition and loyalty, allows premium pricing and differentiates the product.')
a('116. Channels: direct (producer to consumer); via retailer; via wholesaler and retailer. Physical = shops/physical delivery; digital = online sales/downloads (wider reach, lower cost, 24/7).')
a('117. Premium smartphone: Product - high quality, strong USP/brand; Price - skimming (high launch price); Promotion - advertising + digital/influencers to build image; Place - selective/exclusive plus online. Judgement: the 4Ps must be consistent with a premium image; price and promotion likely the most important elements.')

ah1('TOPIC 4: Operations Management')
a('118. Inputs (land, labour, capital, materials) are transformed by a process into outputs (finished goods/services) that have greater value.')
a('119. Operations add value by turning inputs into outputs worth more than the input cost - through quality, design, assembly, branding and service.')
a('120. Efficiency = minimum waste/cost. Effectiveness = meeting objectives/needs. Productivity = output per unit of input. Sustainability = operating without harming future generations/environment.')
a('121. Labour productivity = 12,000 / 40 = 300 units per worker per week.')
a('122. Benefits: lower long-run costs (energy/waste), better image, meets regulation, attracts customers. Drawbacks: high initial cost, may raise prices short term. Analyse both.')
a('123. Capital-intensive: consistent quality, high output, lower long-run unit cost, but high setup cost and inflexible. Labour-intensive: flexible, lower setup, personal service, but wage costs and variable quality.')
a('124. Job = one-off custom product. Batch = groups of identical products made in stages. Flow = continuous mass production. Mass customisation = flow methods that still allow customer tailoring.')
a('125. High cost of new equipment; retraining staff; disruption/downtime during changeover; staff resistance/possible redundancies; less flexibility once flow is set up.')
a('126. Raw materials, work in progress, finished goods.')
a('127. Benefits: meet demand, avoid stock-outs, cope with delivery delays, keep production running. Costs: storage cost, capital tied up (opportunity cost), risk of waste/obsolescence/theft.')
a('128. Buffer inventory = minimum safety stock held. Re-order level = stock level at which a new order is placed. Lead time = time between placing and receiving an order.')
a('129. Stock falls steadily as it is used in production; when a delivery arrives at the re-order point (after the lead time) it jumps back up towards the maximum - the saw-tooth pattern.')
a('130. SCM manages the flow of goods from supplier to customer - reliable, low-cost, good-quality supply improves efficiency, cash flow and customer satisfaction.')
a('131. JIT: stock arrives just when needed, little held - reduces storage costs/waste, frees capital, but no buffer so vulnerable to delays and needs reliable suppliers. JIC: holds buffer stock - never runs out but higher storage cost and waste risk. Analyse the trade-off.')
a('132. Capacity utilisation = (150/200) x 100 = 75%.')
a('133. Low: high fixed cost per unit, wasted resources, staff insecurity (but room to grow). At 100%: no time for maintenance, staff stress, quality may fall, cannot meet extra orders.')
a('134. Increase demand (marketing/new products), reduce capacity (rationalisation), subcontract work in, cut prices to boost sales.')
a('135. Benefits: lower costs, specialist skills, flexibility, focus on core activity. Drawbacks: less control of quality, reliability risk, communication issues, possible job losses/morale, confidentiality risk.')

ah1('TOPIC 5: Finance and Accounting')
a('136. Start-up: premises, equipment, initial stock. Growth: new premises/machinery, R&D, marketing. Survival: wages, rent, materials, day-to-day bills.')
a('137. Short-term = to fund day-to-day/working capital (overdraft, trade credit). Long-term = to fund non-current assets/expansion (loans, shares, mortgages).')
a('138. Cash = money available now to pay bills. Profit = revenue minus total costs over a period. A profitable firm can fail if cash is tied up in stock or late-paying customers so it cannot pay bills (insolvency).')
a('139. Bankruptcy = an individual legally declared unable to pay debts. Liquidation = a company is closed and assets sold to repay creditors. Administration = an insolvent company is run by an administrator to try to rescue it.')
a('140. Working capital = 80,000 - 55,000 = $25,000 positive - the firm can cover short-term debts; not too high, so resources are not idle.')
a('141. Receivables: credit checks, prompt invoicing/chasing, early-payment discounts, shorter credit terms. Payables: negotiate longer credit to hold cash longer without harming supplier relations.')
a('142. Capital expenditure = spending on non-current (fixed) assets (machinery, buildings) - long-term. Revenue expenditure = day-to-day running costs (wages, materials, rent).')
a('143. Sole traders/partnerships rely on savings, loans, retained profit (limited); Ltd can sell shares privately; Plc can sell shares to the public - the incorporated forms with limited liability access more finance.')
a('144. Internal: owners investment, retained earnings, sale of unwanted assets, sale and leaseback, working capital. External: share capital, debentures, new partners, venture capital, overdraft, leasing, hire purchase, bank loans, mortgages, debt factoring, trade credit, micro-finance, crowdfunding, government grants.')
a('145. Debt factoring: sell receivables to a factor for immediate cash. Sale and leaseback: sell an asset then lease it back. Venture capital: investment into high-risk firms for a share. Crowdfunding: many people fund online. Micro-finance: small loans (developing economies). Trade credit: buy now, pay supplier later.')
a('146. Cost (interest/fees), flexibility, need to retain control (shares dilute control), the use/purpose (match term to need), level of existing debt (gearing), amount needed, form of ownership.')
a('147. (a) Sole trader $3,000 laptop: own savings, trade credit or a small bank loan - cheap, simple, no loss of control. (b) Plc $40m factory: share issue or long-term bank loan/debentures/mortgage - only these raise such large long-term sums. Justify by cost, term and control.')
a('148. Cash flow forecast = a prediction of future cash inflows and outflows. Reasons: spot shortages early, arrange finance in advance, plan spending, support a loan application.')
a('149. Net cash flow = 22,000 - 26,000 = -$4,000. Closing balance = 5,000 + (-4,000) = $1,000 (this is April opening balance).')
a('150. Speed up inflows (chase receivables, early-payment discounts, reduce credit period, sell assets); slow outflows (negotiate longer supplier credit, lease not buy, delay non-essential spending); arrange an overdraft; reduce stock held.')
a('151. Fixed = do not change with output (rent). Variable = change with output (raw materials). Direct = clearly linked to a product (its materials). Indirect (overheads) = not linked to one product (admin).')
a('152. Total cost = 20,000 + (6 x 5,000) = 20,000 + 30,000 = $50,000. Average cost = 50,000 / 5,000 = $10 per unit.')
a('153. Full (absorption) costing allocates all costs (direct + a share of overheads) to each product. Contribution (marginal) costing allocates only variable/direct costs to products and treats fixed costs as one total.')
a('154. Contribution = selling price - variable cost (per unit or total); it first covers fixed costs. Profit is only what remains AFTER fixed costs are covered.')
a('155. Contribution per unit = 15 - 9 = $6. Total contribution = 6 x 8,000 = $48,000. Profit = 48,000 - 30,000 = $18,000.')
a('156. Accept a special order if its price is above the variable cost per unit (positive contribution) and there is spare capacity, and it does not harm normal-price sales - the extra contribution adds to profit as fixed costs are already covered.')
a('157. Ignores how fixed costs are shared between products; less useful for setting a full long-term price; may lead to under-pricing if fixed costs are forgotten.')
a('158. Break-even = the output where total revenue = total costs (no profit/loss). Break-even output = fixed costs / contribution per unit.')
a('159. (a) Contribution = 20 - 12 = $8. (b) Break-even = 48,000 / 8 = 6,000 units. (c) Margin of safety = 8,000 - 6,000 = 2,000 units. (d) Profit = (8 x 8,000) - 48,000 = 64,000 - 48,000 = $16,000.')
a('160. Margin of safety = how far current output is above break-even - i.e. how much sales could fall before the firm makes a loss. A larger margin means lower risk.')
a('161. Uses: find break-even, output needed for a target profit, effect of price/cost changes, margin of safety. Limitations: assumes all output is sold, assumes constant price/costs, fixed costs can step up, ignores market changes; only as good as the data.')
a('162. Budget = a financial plan/target for a future period. Uses: measure performance, allocate resources, control/monitor spending, coordinate departments, motivate via targets.')
a('163. Incremental = last period budget adjusted by a % (simple but repeats past errors). Flexible = adjusts with actual output/activity (more realistic). Zero-based = starts from zero, every cost must be justified (avoids waste but time-consuming).')
a('164. Benefits: control spending, aid planning/coordination, motivate, spot problems early. Drawbacks: time-consuming, may be inaccurate, can demotivate if unrealistic/imposed, may cause departmental rivalry.')
a('165. Favourable variance = actual result better than budget (higher revenue or lower costs). Adverse variance = actual result worse (lower revenue or higher costs).')
a('166. Sales: 54,000 - 60,000 = -$6,000 ADVERSE (revenue below budget). Costs: 37,000 - 40,000 = actual $3,000 lower than budget = FAVOURABLE. Net effect on profit: -6,000 + 3,000 = $3,000 worse than budgeted.')
a('167. Budgets aid planning, control and motivation and highlight variances for action, BUT only if realistic, accurate and agreed with staff. Unrealistic or imposed budgets demotivate and can be quickly outdated. Judgement: budgeting improves performance only when set well and used flexibly.')

asp()
A.append(('body', 'END OF ANSWERS - Use these as indicative points; apply to the case and justify judgements in the exam.'))

# ----------------------------------------------------------------------------
pdfgen.build_pdf(Q, 'AS_Business_9609_Question_Bank.pdf',
                 footer_prefix='9609 Question Bank - Page')
pdfgen.build_pdf(A, 'AS_Business_9609_Answers.pdf',
                 footer_prefix='9609 Answers - Page')
print('PDFs generated.')
