# -*- coding: utf-8 -*-
"""Builds AS_Business_9609_Exam_Technique.pdf into the cloned repo folder."""
import pdfgen

B = []
def p(t): B.append(('body', t))
def bu(t): B.append(('bullet', t))
def h1(t): B.append(('h1', t))
def h2(t): B.append(('h2', t))
def h3(t): B.append(('h3', t))
def sp(): B.append(('spacer', ''))

B.append(('title', 'AS Business 9609 - Exam Technique'))
p('How to lay out 3, 5, 8 and 12 mark answers to pick up every available mark. '
  'For the Oct/Nov 2026 exam (syllabus 2026-2028). Includes worked model answers.')
sp()

h1('1. Match your effort to the marks')
p('The mark tariff tells you how much to write and which skills are tested:')
bu('2 marks - "Define / State" - tests Knowledge only. A precise definition (2 elements) OR two stated items. One or two sentences. About 3 minutes.')
bu('3 marks - "Define / State / Identify" - tests Knowledge (+ a little Application). Write a precise definition plus a brief example. About 4 minutes.')
bu('5 marks - "Explain" - tests Knowledge + Application + a little Analysis. Point, define, apply, then develop ONE step. About 6 minutes.')
bu('8 marks - "Analyse" - tests Knowledge + Application + Analysis. Two developed chains. No judgement. About 10 minutes.')
bu('12 marks - "Evaluate / Discuss / Recommend / To what extent" - tests Knowledge + Application + Analysis + Evaluation. Two developed chains PLUS a weighed judgement. About 15 minutes.')

h1('2. The four skills (Assessment Objectives)')
bu('[K] Knowledge (AO1): define and state relevant terms and theory.')
bu('[App] Application (AO2): use the specific business/context given in the question.')
bu('[An] Analysis (AO3): develop cause-and-effect chains - push each point to its final effect on the business.')
bu('[Ev] Evaluation (AO4): make and justify a judgement. Needed ONLY on 12 (and higher) mark questions.')

# ---------------- 2 MARK ----------------
h1('3. The 2-mark layout - "Define / State"')
p('Recipe: a precise definition made of TWO parts [K], OR two clearly stated items.')
p('Template (define): [Term] is [part 1 of definition] [K] which [part 2 of definition] [K].')
p('Template (state two): Two [items] are [item 1] [K] and [item 2] [K].')
bu('Usually 1 mark per correct element. Keep it to one or two sentences.')
bu('Do: use the exact key words. Do NOT: give examples, explanations or chains - there are no marks for them here.')
h3('Worked example - "Define opportunity cost" [2]')
p('Opportunity cost is the benefit of the next best alternative [K] that is given up when a choice is made [K].')
h3('Worked example - "State two factors of production" [2]')
p('Two factors of production are land [K] and labour [K].')

# ---------------- 3 MARK ----------------
h1('4. The 3-mark layout - "Define / State"')
p('Recipe: Definition [K] + a short example or extra detail [K/App].')
p('Template: [Term] is [clear precise definition]. For example, [quick example].')
bu('2 marks for the definition, 1 for the example/expansion.')
bu('Do: use the exact key words. Do NOT: explain consequences or write chains.')
h3('Worked example - "Define added value" [3]')
p('Added value is the difference between the selling price of a product and the cost of the bought-in materials used to make it [K]. For example, a coffee shop buying beans for $0.30 and selling a coffee for $3.00 adds $2.70 of value [App].')

# ---------------- 5 MARK ----------------
h1('5. The 5-mark layout - "Explain"')
p('Recipe: Point, then define [K], then apply to the business [App], then develop ONE step [An].')
p('Template: One [benefit/reason] is [point], which means [define] [K]. In the case of [business/context] this [apply] [App], so [one consequence] [An].')
bu('If the question says "Explain two...", write two shorter versions (about 2-3 marks each).')
bu('Do: always link to the context. Do NOT: write a full evaluation or list undeveloped points.')
h3('Worked example - "Explain one benefit to a firm of low labour turnover" [5]')
p('One benefit is a more experienced workforce [K], as fewer staff leave so skills are retained [K]. For a manufacturer relying on skilled machine operators [App], this means higher quality and productivity [An] and lower recruitment and training costs [An].')

# ---------------- 8 MARK ----------------
h1('6. The 8-mark layout - "Analyse"')
p('Recipe: TWO points. Each = Point, define [K], apply [App], then chain 2-3 steps: because... which leads to... therefore... [An].')
p('Paragraph template (write it twice): One [way/benefit/drawback] is [point] [K]. This means [define] [K]. For [business/context] this [apply] [App]. As a result [effect 1] [An], which in turn [effect 2] [An], meaning [final effect on profit/costs/competitiveness] [An].')
bu('The key skill is CHAINS - push each point to its final business effect; do not stop at the first consequence.')
bu('Do NOT write an introduction or a conclusion. Go straight into Point 1.')
p('Analysis connectives: this means... because... which leads to... as a result... this in turn... therefore... ultimately...')
h3('Worked model - "Analyse two ways business enterprise can help the development of a country" [8]')
p('Point 1 - Job creation: One way business enterprise helps development is by creating employment [K]. Enterprise involves entrepreneurs setting up and expanding businesses that combine the factors of production and must hire workers [K]. In a developing country where unemployment is high [App], these new businesses employ local people [App]. As a result more households earn an income [An], so they spend more in the local economy [An], which raises demand for other firms and creates further jobs through a multiplier effect [An], gradually raising living standards and reducing poverty [An].')
p('Point 2 - Higher output and tax revenue: A second way is by increasing national output (GDP) and tax revenue [K]. As enterprises produce and sell goods and services they add value and generate profits and wages [K]. In a developing economy [App] this extra output raises GDP and means firms and workers pay more corporate and income tax [App/An]. As a result the government receives more revenue [An], which it can invest in infrastructure, education and healthcare [An], improving the workforce productivity and quality of life and driving further long-term development [An].')
p('Note: there is NO judgement - an 8-mark analyse question does not need one.')

# ---------------- 12 MARK ----------------
h1('7. The 12-mark layout - "Evaluate / Recommend / Discuss"')
p('Structure: (optional 1-line intro), Argument 1 as a full chain, Argument 2 or counter as a full chain, then the JUDGEMENT.')
bu('Argument FOR / benefit - same chain as an 8-marker (K + App + An).')
bu('Argument AGAINST / drawback / alternative - another full applied chain.')
bu('Judgement [Ev] - where the top marks are. Include: a clear decision; WHY one side outweighs the other (rank them); an "it depends on..." named factor; a short-term vs long-term point; and a link back to the specific business.')
p('Judgement sentence starters:')
bu('"Overall, the most important factor is X, because..."')
bu('"This depends largely on [named factor]: if [condition] then [choice A], but if [condition] then [choice B]..."')
bu('"In the short term [effect], but in the long term [effect], so on balance..."')
bu('"Therefore I recommend X, provided that [condition]."')
bu('Do: spend about a third of your time on the judgement. Do NOT: stop after two arguments - no judgement caps you at about half marks.')
h3('Worked model - "Intrapreneurship is the most important factor that will ensure the success of a computer entertainment business." Evaluate this view. [12]')
p('Intro: Intrapreneurship means employees using entrepreneurial skills to innovate within an existing business [K], and its importance to a games company must be weighed against other success factors.')
p('FOR: Intrapreneurship is important because success in computer entertainment depends on constant innovation [App]. Intrapreneurs generate new game ideas, features and technologies from within the business [K/App]. This means the company keeps launching fresh titles [An], helping it stay ahead of fast-moving competitors [An], attracting and retaining players [An], leading to repeat sales, a strong brand and higher long-term profit [An].')
p('AGAINST: However, intrapreneurship alone cannot guarantee success. Finance and marketing may matter more [K]. Even the most innovative game needs large sums to fund long development and testing [App]; without enough finance it may never be completed or launched at poor quality [An], so it fails despite good ideas [An]. Equally, the market is crowded, so without effective marketing and branding [K/App] customers will not know the product exists [An], meaning low sales even for an excellent game [An].')
p('JUDGEMENT: Overall, intrapreneurship is a major factor but not necessarily THE most important [Ev]. It is necessary but not sufficient - the innovation it produces only creates success if supported by finance to develop the games and marketing to sell them [Ev]. Its importance also depends on the situation [Ev]: for a new start-up studio, securing finance is probably most critical in the short term, whereas for an established studio intrapreneurship is the key to staying competitive in the long term [Ev]. Therefore the statement is only partly true: intrapreneurship drives the long-term innovation this industry relies on, but the single most important factor changes with the business size, stage and objectives, so it must be combined with sound finance and marketing rather than relied on alone [Ev].')

# ---------------- SUMMARY ----------------
h1('8. One-look revision card')
p('2 marks: definition (2 parts) or two stated items. K yes, App no, An no, Ev no. No example needed.')
p('3 marks: 1 definition. K yes, App small, An no, Ev no. No intro/conclusion.')
p('5 marks: 1-2 points. K yes, App yes, An one step, Ev no. No intro/conclusion.')
p('8 marks: 2 points. K yes, App yes, An 2-3 steps, Ev no. No intro/conclusion.')
p('12 marks: 2 points + judgement. K yes, App yes, An 2-3 steps, Ev ESSENTIAL. Judgement only, no long intro.')

h1('9. Where each mark physically goes in a sentence')
p('Use this fixed order in EVERY explain/analyse/evaluate paragraph. Keep the order the same and you never forget a mark:')
bu('[K] goes FIRST - your opening point + the definition of the key term. (Sentence 1.)')
bu('[App] goes SECOND - straight after the K, name and use the actual business/product/situation from the question. (Sentence 2.)')
bu('[An] goes THIRD - the "so.../which means.../as a result..." chain that pushes the applied point to its final effect on the business. (Sentences 3-4.)')
bu('[Ev] goes LAST - only on 12-mark questions - a separate judgement paragraph at the end.')
p('Formula to memorise: K -> App -> An (-> Ev). Define it, place it in the business, develop it, then (if 12 marks) judge it.')

h1('10. Worked example A - 5 marks "Explain" [K + App + An]')
h3('Question: Explain one benefit to a new business of using penetration pricing. [5]')
h3('Where each mark goes (structure)')
bu('Sentence 1 = your point + define the term -> put [K] here.')
bu('Sentence 2 = link to THIS new business -> put [App] here.')
bu('Sentence 3 = one developed consequence -> put [An] here.')
h3('Model answer (every mark tagged)')
p('One benefit of penetration pricing is that it wins customers quickly [K], because penetration pricing means deliberately setting a low initial price to enter a market [K]. For a new smartphone-app business launching into a market full of established rivals [App], a low launch price persuades price-sensitive users to try the app instead of competitors\' [App]. This means the business rapidly builds market share [An], which spreads its fixed costs over more sales and creates word-of-mouth that fuels future growth [An].')
h3('Key words to drop in')
bu('penetration pricing, low initial price, price-sensitive, market share, competitors, spread fixed costs / economies of scale.')
h3('Ask myself')
bu('Have I DEFINED the key term? (that is my K)')
bu('Have I named and used the actual business in the question? (that is my App)')
bu('Have I pushed the point one more step to a business effect - sales, costs, share? (that is my An)')
bu('Have I resisted writing a judgement? (not needed at 5 marks)')

h1('11. Worked example B - 5 marks "Explain" [K + App + An]')
h3('Question: Explain one way training could improve productivity at a car factory. [5]')
h3('Where each mark goes (structure)')
bu('Sentence 1 = point + define "training" -> [K].')
bu('Sentence 2 = apply to the car factory specifically -> [App].')
bu('Sentence 3 = chain to a productivity effect -> [An].')
h3('Model answer (every mark tagged)')
p('One way is that training gives workers new skills [K], since training means teaching employees the knowledge and abilities needed to do their job [K]. At the car factory, workers trained to operate the assembly-line robots correctly [App] make fewer mistakes and work faster [App]. As a result more cars are produced per worker each hour [An], which raises labour productivity and lowers the labour cost per car [An].')
h3('Key words to drop in')
bu('training, on-the-job / off-the-job, skills, productivity (output per worker), quality, unit/labour cost.')
h3('Ask myself')
bu('Did I define training? (K)')
bu('Did I mention the car factory / assembly line, not a generic firm? (App)')
bu('Did I finish on a measurable effect - more output per worker, lower cost? (An)')

h1('12. Worked example C - 8 marks "Analyse" [K + App + An, no judgement]')
h3('Question: Analyse two benefits to a supermarket of using market segmentation. [8]')
h3('Where each mark goes (structure)')
bu('TWO paragraphs. In each: point + define -> [K]; apply to the supermarket -> [App]; then a 2-3 step chain -> [An].')
bu('NO introduction and NO conclusion - go straight into Point 1. An 8-marker needs no judgement.')
h3('Model answer (every mark tagged)')
p('Point 1 - Precise targeting: One benefit is that segmentation lets the supermarket target its marketing more precisely [K]. Market segmentation means dividing customers into groups with similar characteristics [K]. The supermarket could split shoppers into budget families and higher-income health-conscious buyers [App]. As a result it can promote value ranges to one group and premium organic ranges to the other [App], which means less marketing spend is wasted [An] and each group finds products matching its needs [An], leading to higher sales and stronger customer loyalty [An].')
p('Point 2 - Spotting gaps: A second benefit is the ability to identify and fill gaps in the market [K]. By analysing each segment\'s buying data [App], the supermarket may find unmet demand, such as ready-made vegan meals [App]. This means it can launch products rivals do not offer [An], differentiating itself [An] and attracting new customers who then also buy their weekly groceries there [An], raising total revenue [An].')
p('Note: there is deliberately NO judgement - an 8-mark "analyse" question does not reward one.')
h3('Key words to drop in')
bu('market segmentation, demographic / psychographic, target market, differentiate, customer loyalty, gap in the market.')
h3('Ask myself')
bu('Have I written TWO clearly separate points? (not one point twice)')
bu('Did I define the term in each point? (K)')
bu('Did I apply to the supermarket specifically, not "a business"? (App)')
bu('Does each chain end on a business effect - sales, revenue, loyalty, costs? (An)')
bu('Did I resist adding a conclusion? (it earns nothing extra at 8 marks and wastes time)')

h1('13. Worked example D - 12 marks "Evaluate" [K + App + An + Ev]')
h3('Question: A sole trader wants to expand her bakery. Evaluate whether she should use a bank loan to finance the expansion. [12]')
h3('Where each mark goes (structure)')
bu('One-line intro: define "bank loan" -> [K] and set up the weigh-up.')
bu('Argument FOR: point + define -> [K]; apply to her bakery -> [App]; chain -> [An].')
bu('Argument AGAINST / alternative: point + define -> [K]; apply -> [App]; chain -> [An].')
bu('Judgement paragraph = ALL your [Ev] marks. This is where the top marks live - about a third of the answer.')
h3('Model answer (every mark tagged)')
p('Intro: A bank loan is a sum borrowed from a bank and repaid with interest over an agreed period [K]. Whether it is the best way to fund the bakery\'s expansion depends on weighing its benefits against the risks and the alternatives.')
p('FOR: A key advantage is that a loan provides a large lump sum while the owner keeps full control [K]. As a sole trader she does not have to take on partners or shareholders [App], so she keeps all decision-making and profit [App]. This means she can buy the new oven and premises straight away [An], raising output and sales [An], while repayments spread over several years keep monthly cash flow manageable [An].')
p('AGAINST: However, a loan adds a fixed interest cost that must be paid whether or not sales rise [K]. Because a small bakery has seasonal, uncertain demand [App], in a quiet month she could struggle to meet repayments [An], which raises her break-even output and her risk of insolvency [An]. Retained profit or leasing the equipment might be cheaper and lower-risk [K/App].')
p('JUDGEMENT: Overall, a bank loan is a reasonable choice but only under certain conditions [Ev]. It is most suitable if the expansion is forecast to raise sales enough to comfortably cover repayments, and if she holds some savings as a buffer [Ev]. In the short term the interest raises her costs and risk, but in the long term the extra capacity should raise profit, so the decision hinges on how confident she is in future demand [Ev]. Given she is a sole trader with unlimited liability, I would recommend she borrow a smaller amount and top it up with retained profit, so she gains the capacity to expand without over-exposing her personal assets [Ev].')
h3('Key words to drop in')
bu('bank loan, interest, collateral, fixed cost, break-even output, cash flow, unlimited liability, retained profit, leasing.')
h3('Ask myself (the evaluation checklist - this earns the [Ev] marks)')
bu('Did I give a CLEAR decision (yes / no / which one)?')
bu('Did I say WHY one side outweighs the other (rank them)?')
bu('Did I include an "it depends on..." named factor?')
bu('Did I contrast SHORT term vs LONG term?')
bu('Did I link the judgement back to THIS specific business (a sole-trader bakery)?')
bu('Did I spend roughly a third of my time/space on the judgement?')

h1('14. The three biggest mark-losers to avoid')
bu('Not linking to the business given in the question - you lose all Application marks.')
bu('Listing many points without developing them - you lose Analysis marks. Fewer, deeper chains score higher.')
bu('Writing no judgement on a 12-mark question - you cap your mark at roughly half.')
sp()
B.append(('body', 'Apply every point to the specific business and justify your judgements to reach the top mark bands.'))

pages = pdfgen.build_pdf(
    B, '/projects/sandbox/Business-AS-level-/AS_Business_9609_Exam_Technique.pdf',
    footer_prefix='Exam Technique - Page')
print('Exam technique PDF:', pages, 'pages')
